install.packages("mlbench")
library("mlbench")
mlbench.1spiral(10,1,1)

install.packages("sonar")
library(sonar)
sonar::AbsorptionAlphaAinslieMcColm(90,12,1,1,7)
str(SonarEquation)
install.packages("caret")
install.packages("ggplot2")
library(caret)
